title: "ธรรมสุตตะ"
description: "แหล่งรวมพระไตรปิฎก พร้อมธรรมบรรยาย บทสวด และชาดก"
url: "https://dhamsutta.github.io"
baseurl: "/tripitaka-site"
repository: "dhamsutta/tripitaka-site"

# Theme settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

# SEO
logo: "/assets/images/placeholder-logo.png"
favicon: "/assets/images/placeholder-logo.png"
locale: "th"
lang: "th"

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives
  - jekyll-remote-theme

markdown: kramdown
highlighter: rouge

# Navigation
collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  -
    scope:
      path: ""
    values:
      custom_css: "/assets/css/custom.css"

# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/dhamsutta"
